service: serverlessr-test
provider:
  name: aws
  profile: nadir-personal
  runtime: provided
  stage: dev
  region: us-east-2
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
          - - Ref: ServerlessDeploymentBucket

functions:
  test-function:
    handler: plumber
    layers:
      - arn:aws:lambda:us-east-2:144438831032:layer:R-3_6_3-RookRuntime:20
      # - arn:aws:lambda:us-east-2:144438831032:layer:R-3_6_3-plumber:9
    environment:
      LOGLEVEL: DEBUG
    events:
      - http:
          method: post
          path: /echo
          # integration: lambda
          # request:
          #   template:
          #     application/json: '$input.body'
