service: serverlessr-test
provider:
  name: aws
  profile: nadir-personal
  runtime: provided
  stage: dev
  region: us-east-2
  memorySize: 128
functions:
  test-function:
    handler: script.handler
    layers:
      - arn:aws:lambda:us-east-2:144438831032:layer:R-3_6_3-RookRuntime:4
    environment:
      LOGLEVEL: DEBUG
    events:
      - http:
          method: post
          path: /
          # integration: lambda
          # request:
          #   template:
          #     application/json: '$input.body'
